![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [ ]:
royxat = [1, 2, 3, 4, 5]
massiv = np.array(royxat)
print(massiv)

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz oʻlchovli massiv yarating.



`💡Ishora` np.zeros

In [2]:
import numpy as np
massiv = np.zeros((1, 1, 1, 1, 1, 1, 1, 1, 1))
print("Massiv shakli:", massiv.shape)
print("Massiv o'zi:\n", massiv)

Massiv shakli: (1, 1, 1, 1, 1, 1, 1, 1, 1)
Massiv o'zi:
 [[[[[[[[[0.]]]]]]]]]


#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [3]:
a = np.array([1, 2, 3, 4, 5])
print("Har bir element hajmi:", a.itemsize, "bayt")

Har bir element hajmi: 8 bayt


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [4]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [ ]:
vektor = np.zeros(12)
vektor[5] = 1
print("Vektor:", vektor)

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [ ]:
vektor = np.arange(20, 60)

print("Vektor:", vektor)

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [6]:
vektor =np.arange(1,11)
teskari_vektor = vektor[::-1]
print(teskari_vektor)

[10  9  8  7  6  5  4  3  2  1]


#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [7]:
sonlar = np.arange(12, 21)
matritsa = sonlar.reshape(3, 3)
print("3x3 matritsa:\n", matritsa)

3x3 matritsa:
 [[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [8]:
vektor = np.array([3, 7, 0, 0, 9, 0])
indekslar = np.nonzero(vektor)
print("Nolga teng bo'lmagan elementlar indekslari:", indekslar[0])

Nolga teng bo'lmagan elementlar indekslari: [0 1 4]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [9]:
massiv = np.random.rand(2, 2, 2)

print("2x2x2 tasodifiy massiv:\n", massiv)

2x2x2 tasodifiy massiv:
 [[[0.97413942 0.73394853]
  [0.29818002 0.12488493]]

 [[0.47849294 0.21856766]
  [0.27401803 0.98196867]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [10]:
massiv = np.random.rand(9, 9)
eng_katta = np.max(massiv)
eng_kichik = np.min(massiv)
print("Massiv:\n", massiv)
print("\nEng katta qiymat:", eng_katta)
print("Eng kichik qiymat:", eng_kichik)

Massiv:
 [[0.03167602 0.65874229 0.21318027 0.35559536 0.75370778 0.89460258
  0.84768272 0.73774386 0.69354745]
 [0.49779914 0.21591578 0.17263757 0.14106318 0.90060961 0.89030373
  0.57922281 0.05063623 0.88981555]
 [0.42789059 0.00563713 0.18442245 0.61289456 0.56746208 0.52928768
  0.30372548 0.61975388 0.61980469]
 [0.19376344 0.44753179 0.92207598 0.23430863 0.71510072 0.85382001
  0.88749847 0.32493406 0.28972389]
 [0.98791183 0.74141184 0.05315133 0.146875   0.24958846 0.3426364
  0.65618113 0.54735312 0.15390059]
 [0.55064511 0.00402772 0.84045335 0.22011773 0.6096949  0.9499138
  0.09686668 0.19956261 0.36139814]
 [0.212816   0.52064175 0.53408301 0.04091084 0.14572187 0.71328376
  0.70588154 0.78272108 0.81011858]
 [0.31131848 0.2490827  0.90647081 0.89154726 0.7607222  0.56248465
  0.88378214 0.43333927 0.757708  ]
 [0.2462572  0.5186849  0.11592476 0.66766611 0.58124789 0.36019096
  0.77459929 0.86485845 0.29794907]]

Eng katta qiymat: 0.9879118292330897
Eng kichik qiymat:

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [11]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [12]:
A = np.random.randint(0, 10, size=(6, 3))  # 6x3 matritsa
B = np.random.randint(0, 10, size=(3, 4))  # 3x4 matritsa
C = np.dot(A, B)

print("Matritsa A (6x3):\n", A)
print("\nMatritsa B (3x4):\n", B)
print("\nKo'paytma C = A × B (6x4):\n", C)

Matritsa A (6x3):
 [[4 2 7]
 [2 7 3]
 [7 8 2]
 [2 3 2]
 [6 7 9]
 [8 2 6]]

Matritsa B (3x4):
 [[4 8 3 0]
 [7 8 1 9]
 [7 5 8 6]]

Ko'paytma C = A × B (6x4):
 [[ 79  83  70  60]
 [ 78  87  37  81]
 [ 98 130  45  84]
 [ 43  50  25  39]
 [136 149  97 117]
 [ 88 110  74  54]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [14]:
a = np.array([1, 2])
b = np.array([4, 5])

# Elementlar bo‘yicha taqqoslash
print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a <= b:", a <= b)

a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-15-548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipython-input-15-548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipython-input-15-548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
umumiy = np.intersect1d(a, b)

print("Massiv a:", a)
print("Massiv b:", b)
print("Umumiy qiymatlar:", umumiy)

Massiv a: [1 2 3 4 5]
Massiv b: [4 5 6 7 8]
Umumiy qiymatlar: [4 5]


#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [17]:
massiv = np.random.uniform(-10, 10, size=10)

print("Asl massiv:", massiv)

Asl massiv: [-9.71807728  5.79296625  0.18190575  0.37210595 -2.3169753   0.29074868
  2.83212174 -5.79401565 -6.53864339 -2.47628705]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [18]:
matritsa = np.tile(np.arange(3), (3, 1))

print("3x3 matritsa:\n", matritsa)

3x3 matritsa:
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [19]:
vektor = np.random.randint(0, 100, size=10)
saralangan = np.sort(vektor)

print("Asl vektor:", vektor)
print("Saralangan vektor:", saralangan)

Asl vektor: [31 84 94 64 44 95 71 14 69 85]
Saralangan vektor: [14 31 44 64 69 71 84 85 94 95]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [20]:
A = np.random.randint(0, 10, size=5)
B = np.random.randint(0, 10, size=5)

# Elementlar bo'yicha tenglikni tekshirish
element_tenglik = A == B

# Umuman tengligini tekshirish (faqat agar hammasi bir xil bo‘lsa True bo'ladi)
massivlar_tengmi = np.array_equal(A, B)

print("Massiv A:", A)
print("Massiv B:", B)
print("Elementlar bo'yicha tenglik:", element_tenglik)
print("Umuman tengmi (array_equal):", massivlar_tengmi)

Massiv A: [2 6 8 4 3]
Massiv B: [3 7 1 3 2]
Elementlar bo'yicha tenglik: [False False False False False]
Umuman tengmi (array_equal): False


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [21]:
# 6x3 o'lchamdagi matritsa (tasodifiy butun sonlar)
A = np.random.randint(0, 10, size=(6, 3))

# 3x4 o'lchamdagi matritsa (tasodifiy butun sonlar)
B = np.random.randint(0, 10, size=(3, 4))

# Matritsalarni ko'paytiramiz: A (6x3) × B (3x4) → C (6x4)
C = np.dot(A, B)

# Natijalarni chiqaramiz
print("Matritsa A (6x3):\n", A)
print("\nMatritsa B (3x4):\n", B)
print("\nKo'paytma C = A × B (6x4):\n", C)

Matritsa A (6x3):
 [[5 5 5]
 [9 2 0]
 [9 4 9]
 [9 1 8]
 [9 9 5]
 [6 2 9]]

Matritsa B (3x4):
 [[9 5 7 5]
 [8 1 7 5]
 [0 4 7 0]]

Ko'paytma C = A × B (6x4):
 [[ 85  50 105  50]
 [ 97  47  77  55]
 [113  85 154  65]
 [ 89  78 126  50]
 [153  74 161  90]
 [ 70  68 119  40]]


#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [ ]:
vektor = np.array([3, 7, 2, 9, 5])

indeks = np.argmax(vektor)
qiymat = vektor[indeks]

print("Vektor:", vektor)
print("Eng katta qiymat:", qiymat)
print("Uning indeksi:", indeks)

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
mport numpy as np

# Bugungi sana
bugun = np.datetime64('today')

# Kecha va ertangi sana
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
# 2016-yil yanvarning 1-sanasidan 2016-yil fevralning 1-sanasigacha bo'lgan oraliq
yanvar_sanalari = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

print("2016-yil yanvar sanalari:")
print(yanvar_sanalari)

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [22]:
# 0–10 oralig‘ida 10 ta tasodifiy (musbat) son
x = np.random.uniform(0, 10, size=10)
print("Asl massiv (float):\n", x)

# 1‑usul: np.floor  – pastga yaxlitlaydi
whole1 = np.floor(x)

# 2‑usul: np.trunc  – kasr qismini kesib tashlaydi
whole2 = np.trunc(x)

# 3‑usul: astype(int) – int ga kasting (kasrni tashlab yuboradi)
whole3 = x.astype(int)

# 4‑usul: np.fix  – nol tomonga yaxlitlaydi (musbatlarda floor bilan bir xil)
whole4 = np.fix(x)

print("\n1‑usul (floor):\n", whole1)
print("\n2‑usul (trunc):\n", whole2)
print("\n3‑usul (astype int):\n", whole3)
print("\n4‑usul (fix):\n", whole4)


Asl massiv (float):
 [4.20360013 1.97282597 6.09258244 7.62479007 6.08144783 7.07881796
 5.45343388 3.61616977 0.48562327 5.07267915]

1‑usul (floor):
 [4. 1. 6. 7. 6. 7. 5. 3. 0. 5.]

2‑usul (trunc):
 [4. 1. 6. 7. 6. 7. 5. 3. 0. 5.]

3‑usul (astype int):
 [4 1 6 7 6 7 5 3 0 5]

4‑usul (fix):
 [4. 1. 6. 7. 6. 7. 5. 3. 0. 5.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [25]:
a = np.random.randint(1, 100, size=10)

# np.add.reduce yordamida yig‘indi
sum_reduce = np.add.reduce(a)

print("Massiv:", a)
print("Yig‘indi (np.add.reduce):", sum_reduce)



Massiv: [34 51  4 23 97 78 21 79 90 24]
Yig‘indi (np.add.reduce): 501


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [26]:
arr = np.array([1, 2, 3, 4, 5])

# Har bir elementdan keyin 3 ta nol qo'shish uchun kerakli uzunlik
result = np.zeros(len(arr) * 4 - 3, dtype=int)  # 4 = 1 element + 3 nol

# Har 4-elementda asl qiymatni joylash
result[::4] = arr

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [28]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

window_size = 4
num_windows = len(a) - window_size + 1

# Stride'ni olish
stride = a.strides[0]

# Sliding window massivini yaratish
b = as_strided(a, shape=(num_windows, window_size), strides=(stride, stride))

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [29]:
a = np.random.randint(0, 10, size=20)  # 0 dan 9 gacha bo‘lgan sonlardan 20 tasi

print("Massiv:", a)

counts = np.bincount(a)

print("Qiymatlar chastotasi:", counts)

most_common = np.argmax(counts)

print("Eng ko‘p uchragan qiymat:", most_common)
print("Uchragan soni:", counts[most_common])

Massiv: [5 9 1 0 4 8 8 9 3 7 9 5 7 3 6 8 3 2 4 8]
Qiymatlar chastotasi: [1 1 1 3 2 2 1 2 4 3]
Eng ko‘p uchragan qiymat: 8
Uchragan soni: 4


#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`